require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods:
    - 'describe'
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
